name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies for tests
        run: |
          sudo apt-get update
          # sudo apt-get install -y base-files dash libc-bin libc6:amd64 libpython3.13-stdlib:amd64 locales media-types ncurses-base openssl python3-minimal python3-zope.interface python3.10-minimal python3.13 tzdata

      - name: Install uv
        run: uv pip install uv==0.8.0

      - name: Run tox tests (py3.13)
        run: uv run --locked tox run -e py3.13

  typing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies for typing
        run: |
          sudo apt-get update
          # sudo apt-get install -y base-files ca-certificates libc-bin libc6:amd64 libncursesw6:amd64 libpython3.13-stdlib:amd64 locales ncurses-base openssl python3-minimal python3.13 tzdata

      - name: Install uv
        run: uv pip install uv==0.8.0

      - name: Run tox tests (typing)
        run: uv run --locked tox run -e typing
